getgoui/go-ui

- docs/docs/components/gov-button.mdx
- docs/docusaurus.config.js
- docs/package-lock.json
- docs/package.json
> feat: add docusaurus-plugin-includes

- .husky/commit-msg
- .husky/pre-commit
- CONTRIBUTING.md
- commitlint.config.js
- package-lock.json
- package.json
#7 Changelog generation
- Added tools to lint commit messages to help with change log automation 
- Added guidelines for commit message format
> Changelog gen

- .github/workflows/update-changelog.yml
Generates an automatic changelog as per issue #7
> ci: create changelog when pushing to master

- .github/workflows/update-changelog.yml
Setup github credentials to the GitHub action bot. Credentials found in this post https://github.community/t/github-actions-bot-email-address/17204/4
fixes #31
> fix(ci): fix github action: Update Changelog

- bin/cli.js
- bin/const.js
- bin/gen-component.js
- bin/gen-pattern.js
- bin/help.js
- docs/docs/components/intro.md
- docs/docs/patterns/intro.md
gg cli for pattern boilerplate generation
Changes: 
`gg generate` => `gg component`
added: `gg pattern` for generating a new pattern
> CLI for pattern boilerplate code

- docs/docs/patterns/global-styles/typography.mdx
- docs/docusaurus.config.js
- docs/src/components/Demo.scss
- src/global/scss/_css_variables.scss
- src/global/scss/_typography.scss
- src/global/scss/utils/_mixins.scss
- src/global/scss/utils/_scss_vars.scss
- src/patterns/typography/demo/headings.html
- src/patterns/typography/demo/positions.html
- src/patterns/typography/demo/typography.html
> Typography

- docs/docs/patterns/global-styles/typography.mdx
- docs/src/css/custom.scss
- src/global/scss/_css_variables.scss
- src/global/scss/_typography.scss
- src/global/scss/utils/_scss_vars.scss
- src/patterns/typography/demo/headings.html
- src/patterns/typography/demo/typography.html
> Implement fluid typography

- docs/src/components/Demo.scss
- docs/src/components/Demo.tsx
- src/components/navigation/go-nav-drawer/demo/go-nav-drawer.html
- src/components/navigation/go-nav-drawer/go-nav-drawer.tsx
> fix nav drawer issue

- docs/docs/components/go-toc.mdx
- src/components.d.ts
- src/components/go-toc/demo/go-toc.html
- src/components/go-toc/go-toc.scss
- src/components/go-toc/go-toc.tsx
- src/components/go-toc/readme.md
- src/components/go-toc/test/go-toc.spec.tsx
- src/components/navigation/go-nav-list/demo/go-nav-list.html
- src/global/scss/_css_variables.scss
- src/global/scss/_display.scss
- src/global/scss/_grid.scss
- src/global/scss/_typography.scss
- src/global/scss/utils/_mixins.scss
- src/global/scss/utils/_scss_vars.scss
- src/global/styles.scss
> feat: table of content component

- docs/docs/components/go-breadcrumb.mdx
- src/components.d.ts
- src/components/go-breadcrumb/demo/go-breadcrumb.html
- src/components/go-breadcrumb/go-breadcrumb.scss
- src/components/go-breadcrumb/go-breadcrumb.tsx
- src/components/go-breadcrumb/readme.md
- src/components/go-breadcrumb/test/go-breadcrumb.spec.tsx
> feat: breadcrumb component

- docs/docs/components/go-hero.mdx
- docs/docs/patterns/footer.mdx
- docs/src/components/Demo.tsx
- src/components.d.ts
- src/components/go-hero/demo/go-hero.html
- src/components/go-hero/go-hero.scss
- src/components/go-hero/go-hero.tsx
- src/components/go-hero/readme.md
- src/components/go-hero/test/go-hero.spec.tsx
> feat: hero component

- docs/docs/components/go-badge.mdx
- src/components.d.ts
- src/components/go-badge/demo/go-badge.html
- src/components/go-badge/go-badge.scss
- src/components/go-badge/go-badge.tsx
- src/components/go-badge/readme.md
- src/components/go-badge/test/go-badge.spec.tsx
- src/components/go-button/demo/icons.html
> feat: badge component

- docs/docs/components/go-progress.mdx
- docs/docs/patterns/go-button-group.mdx
- src/components.d.ts
- src/components/go-button/go-button.scss
- src/components/go-progress/demo/go-progress.html
- src/components/go-progress/go-progress.scss
- src/components/go-progress/go-progress.tsx
- src/components/go-progress/readme.md
- src/components/go-progress/test/go-progress.spec.tsx
> feat: progress bar component

- docs/docs/patterns/go-card-row.mdx
- src/components.d.ts
- src/components/go-card/demo/go-card-links.html
- src/components/go-card/demo/go-card.html
- src/components/go-card/go-card.scss
- src/components/go-card/go-card.tsx
- src/components/go-link/go-link.scss
- src/global/scss/_animation.scss
- src/global/scss/_css_variables.scss
- src/patterns/go-card-row/demo/go-card-row-dynamic.html
- src/patterns/go-card-row/demo/go-card-row.html
- src/patterns/go-card-row/go-card-row.scss
- src/patterns/go-card-row/go-card-row.tsx
- src/patterns/go-card-row/readme.md
- src/patterns/go-card-row/test/go-card-row.e2e.ts
> feat: :sparkles: card row pattern

- src/components.d.ts
- src/global/scss/_colors.scss
- src/global/scss/_css_variables.scss
- src/global/scss/_display.scss
- src/global/scss/_flex.scss
- src/global/scss/_misc.scss
- src/global/styles.scss
- src/patterns/go-card-row/demo/go-card-row-dynamic.html
- src/patterns/go-card-row/demo/go-card-row.html
- src/patterns/go-card-row/go-card-row.scss
- src/patterns/go-card-row/go-card-row.tsx
- src/utils/dom.ts
> feat: card row - heading row

- packages/core/src/components.d.ts
- packages/core/src/components/go-hero/go-hero.scss
- packages/core/src/components/go-hero/go-hero.tsx
- packages/core/src/components/go-hero/usage/go-hero.md
- packages/core/src/patterns/go-content-layout/go-content-layout.tsx
> feat: Hero - full width image variations

- docs/src/components/app-header/app-header.tsx
- packages/core/src/components.d.ts
- packages/core/src/components/navigation/go-main-nav/go-main-nav.tsx
- packages/core/src/components/navigation/go-main-nav/usage/go-main-nav.md
- packages/core/src/components/navigation/go-nav-drawer/go-nav-drawer.tsx
- packages/core/src/patterns/go-footer/go-footer.tsx
> fix: optimise nav labels

- package.json
- packages/core/src/components.d.ts
- packages/core/src/components/form/go-checkbox/go-checkbox.scss
- packages/core/src/components/form/go-checkbox/readme.md
- packages/core/src/components/form/go-checkbox/usage/checkbox-fieldset.md
- packages/core/src/components/form/go-radio/go-radio.scss
- packages/core/src/components/form/go-radio/go-radio.tsx
- packages/core/src/components/form/go-radio/readme.md
- packages/core/src/components/form/go-radio/test/go-radio.spec.tsx
- packages/core/src/components/form/go-radio/usage/go-radio.md
- packages/core/src/components/form/go-radio/usage/radio-fieldset.md
- packages/core/src/global/scss/_css_variables.scss
- packages/core/src/global/scss/_fonts.scss
- packages/core/src/global/scss/form/_variables.scss
- packages/core/src/global/styles.scss
- packages/core/src/index.html
- packages/react/src/components/stencil-generated/index.ts
- packages/vue/src/components.ts
- pnpm-lock.yaml
> feat: radio button and style updates

- axe-linter.yml
- packages/core/src/components.d.ts
- packages/core/src/components/go-button/go-button.tsx
- packages/core/src/components/go-dropdown-menu/go-dropdown-item.scss
- packages/core/src/components/go-dropdown-menu/go-dropdown-item.tsx
- packages/core/src/components/go-dropdown-menu/go-dropdown-menu.scss
- packages/core/src/components/go-dropdown-menu/go-dropdown-menu.tsx
- packages/core/src/components/go-dropdown-menu/readme.md
- packages/core/src/components/go-dropdown-menu/test/go-dropdown-menu.spec.tsx
- packages/core/src/components/go-dropdown-menu/usage/go-dropdown-menu.md
- packages/core/src/components/go-dropdown/go-dropdown.scss
- packages/core/src/components/go-dropdown/go-dropdown.tsx
- packages/core/src/components/go-dropdown/readme.md
- packages/core/src/global/scss/utils/_mixins.scss
- packages/core/src/index.html
- packages/core/src/interfaces/dropdown-props.ts
- packages/core/src/interfaces/index.ts
- packages/core/src/utils/dom.ts
> feat: dropdown menu

- packages/core/src/components.d.ts
- packages/core/src/components/go-blockquote/go-blockquote.scss
- packages/core/src/components/go-blockquote/go-blockquote.tsx
- packages/core/src/components/go-blockquote/readme.md
- packages/core/src/components/go-blockquote/test/go-blockquote.spec.tsx
- packages/core/src/components/go-blockquote/usage/go-blockquote.md
> feat: Blockquote

- docs/src/components/demo-playground/wc-playground.scss
- docs/src/components/demo-playground/wc-playground.tsx
- packages/core/src/components/go-card/usage/go-card.md
- packages/core/src/components/go-dropdown-menu/go-dropdown-item.scss
- packages/react/src/components/stencil-generated/index.ts
- packages/vue/src/components.ts
> chore: docs demo fix

- packages/core/src/components.d.ts
- packages/core/src/components/form/go-field/go-field.tsx
- packages/core/src/components/form/go-input/test/go-input.spec.tsx
- packages/core/src/components/form/go-select/go-select.tsx
- packages/core/src/components/form/go-textarea/go-textarea.scss
- packages/core/src/components/form/go-textarea/go-textarea.tsx
- packages/core/src/components/form/go-textarea/readme.md
- packages/core/src/components/form/go-textarea/test/go-textarea.spec.tsx
- packages/core/src/components/form/go-textarea/usage/go-textarea.md
- packages/core/src/components/go-dropdown/go-dropdown.scss
- packages/core/src/components/go-dropdown/go-dropdown.tsx
- packages/core/src/global/scss/form/_mixins.scss
- packages/core/src/global/scss/form/_variables.scss
- packages/core/src/global/styles.scss
- packages/core/src/index.html
- packages/core/src/interfaces/form.ts
- packages/core/src/utils/const.ts
- packages/core/src/utils/dom.ts
- packages/core/src/utils/helper.ts
- packages/core/src/utils/index.ts
- packages/core/src/utils/select.ts
- textarea component
- form field refactor
> feat: textarea component (+field refactor)
